// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnN_OszqD71raD6QNh6m71K_6ShlUDtQE',
    appId: '1:804480431087:web:ce943ce04cf82641b4bc1a',
    messagingSenderId: '804480431087',
    projectId: 'gtu-kuzgun',
    authDomain: 'gtu-kuzgun.firebaseapp.com',
    storageBucket: 'gtu-kuzgun.appspot.com',
    measurementId: 'G-JP9CRK4E0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH3bF65NY4oSiYZ5fRwXG-xvxcX6-qEng',
    appId: '1:804480431087:android:a6ef29366055b44ab4bc1a',
    messagingSenderId: '804480431087',
    projectId: 'gtu-kuzgun',
    storageBucket: 'gtu-kuzgun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw18GJMDdPgCr6_fjB13k98VWBn5Uy5jk',
    appId: '1:804480431087:ios:a6e94e03774493f0b4bc1a',
    messagingSenderId: '804480431087',
    projectId: 'gtu-kuzgun',
    storageBucket: 'gtu-kuzgun.appspot.com',
    iosBundleId: 'com.kuzgun.gtukuzgun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw18GJMDdPgCr6_fjB13k98VWBn5Uy5jk',
    appId: '1:804480431087:ios:a6e94e03774493f0b4bc1a',
    messagingSenderId: '804480431087',
    projectId: 'gtu-kuzgun',
    storageBucket: 'gtu-kuzgun.appspot.com',
    iosBundleId: 'com.kuzgun.gtukuzgun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnN_OszqD71raD6QNh6m71K_6ShlUDtQE',
    appId: '1:804480431087:web:5fbfdf13ca906406b4bc1a',
    messagingSenderId: '804480431087',
    projectId: 'gtu-kuzgun',
    authDomain: 'gtu-kuzgun.firebaseapp.com',
    storageBucket: 'gtu-kuzgun.appspot.com',
    measurementId: 'G-8LCW071VLL',
  );
}
